# Generated by Django 3.0.8 on 2020-07-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200730_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name': 'Участника клуба', 'verbose_name_plural': 'Участники клуба'},
        ),
    ]
