# Generated by Django 3.0.8 on 2020-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=128)),
                ('postText', models.TextField()),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name': 'участника клуба', 'verbose_name_plural': 'участники клуба'},
        ),
    ]
